#ifndef INC_HARDWARE_SCREEN_SSD1306_REGISTERS_H_
#define INC_HARDWARE_SCREEN_SSD1306_REGISTERS_H_

typedef enum{
	SCROLL_HOR_RIGHT	= 0x26,
	SCROLL_HOR_LEFT		= 0x27,
	CONTRAST_CONTROL	= 0x81,
	DISPLAY_FOLLOW_RAM	= 0xA4,
	DISPLAY_ALL_ON		= 0xA5,
	DISPLAY_NORMAL		= 0xA6,
	DISPLAY_INVERSE		= 0xA7,
	DISPLAY_OFF			= 0xAE,
	DISPLAY_ON			= 0xAF,
}SSD1306register_e;

#endif /* INC_HARDWARE_SCREEN_SSD1306_REGISTERS_H_ */
