# SPDX-FileCopyrightText: 2026 Gilles Henrard <contact@gilleshenrard.com>
#
# SPDX-License-Identifier: MIT

name: Feature Request
description: Propose a new feature or improvement for firmware, hardware, or tooling.
title: "[FEAT] <short description>"
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Feature requests are welcome. The more context you provide,
        the easier it is to evaluate and prioritize your proposal.

  - type: dropdown
    id: feature_area
    attributes:
      label: Target Area
      description: Which part of the project would this feature affect?
      options:
        - Firmware
        - PCB / Hardware
        - Enclosure / Mechanical
        - Software tooling (build system, scripts)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What limitation does it address?
      placeholder: "Currently there is no way to ... which means ..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like, as concretely as possible.
      placeholder: "Add a ... that allows the user to ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?

  - type: dropdown
    id: priority
    attributes:
      label: Perceived Priority
      description: How important is this to you?
      options:
        - Nice to have
        - Important
        - Critical / blocking
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Sketches, datasheets, reference implementations, or related issues.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues and this has not been requested before.
          required: true
        - label: This request is scoped to this project (not a general embedded systems question).
          required: true