version = 1

# A simple glob of all files in resources/img/
[[annotations]]
path = "firmware/Core/*"
SPDX-FileCopyrightText = "2024 STMicroelectronics"
#SPDX-License-Identifier = "CC0-1.0"

# All files in resources/vid/, with multiple copyright holders
[[annotations]]
path = "firmware/Drivers/STM32F1xx_HAL_Driver/*"
SPDX-FileCopyrightText = "2019 STMicroelectronics"
SPDX-License-Identifier = "BSD-3-Clause"
