name: Check KiCad schematics
on: 
  push:
    branches: [dev]
    paths:
      - 'schematics/KiCad/*'
  pull_request:
    branches: [dev]
    paths:
      - 'schematics/KiCad/*'

env:
  SCH_PATH: ${{github.workspace}}/schematics/KiCad/leany.kicad_sch

jobs:
    run_checks:
        name: Run KiCad checks
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v4

          - name: Export production files
            id: production
            uses: sparkengineering/kicad-action@v2
            if: '!cancelled()'
            with:
                kicad_sch: ${{env.SCH_PATH}}

          - name: Run Electrical Rules Check (ERC)
            id: erc
            uses: sparkengineering/kicad-action@v2
            if: '!cancelled()'
            with:
                kicad_sch: ${{env.SCH_PATH}}
                sch_erc: true

            # Upload ERC report only if ERC failed
          - name: Upload ERC report
            uses: actions/upload-artifact@v4
            if: ${{ failure() && steps.erc.conclusion == 'failure' }}
            with:
                name: erc.rpt
                path: ${{github.workspace}}/schematics/KiCad/erc.rpt
