name: Check KiCad schematics
on: 
  push:
    paths:
      - 'schematics/KiCad/*'
      - '.github/workflows/verify_kicad.yml'
  pull_request:
    paths:
      - 'schematics/KiCad/*'
      - '.github/workflows/verify_kicad.yml'

env:
  SCH_PATH: ${{github.workspace}}/schematics/KiCad
  SCH_FILE: leany.kicad_sch
  ERC_FILE: erc.json

jobs:
    run_checks:
        name: Run KiCad checks
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v4

          - name: Export production files
            id: production
            uses: sparkengineering/kicad-action@v3
            if: '!cancelled()'
            with:
                kicad_sch: ${{env.SCH_PATH}}/${{env.SCH_FILE}}

          - name: Run Electrical Rules Check (ERC)
            id: erc
            uses: sparkengineering/kicad-action@v3
            if: '!cancelled()'
            with:
                kicad_sch: ${{env.SCH_PATH}}/${{env.SCH_FILE}}
                sch_erc: true
                report_format: json
                sch_erc_file: ${{env.SCH_PATH}}/${{env.ERC_FILE}}

            # Upload ERC report only if ERC failed
          - name: Upload ERC report
            uses: actions/upload-artifact@v4
            if: ${{ failure() && steps.erc.conclusion == 'failure' }}
            with:
                name: ${{env.ERC_FILE}}
                path: ${{env.SCH_PATH}}/${{env.ERC_FILE}}
